import React from "react"

const MVPCoverPage = ({ clientData }) => {
  const { organizationName, reportDate } = clientData.reportMetadata

  return (
    <div className="flex h-full w-full relative overflow-hidden">
      {/* Background with gradient */}
      <div className="absolute inset-0 z-0">
        <div
          className="w-full h-full bg-blue-900"
          style={{
            background: "linear-gradient(to bottom right, #1e3a8a, #000000)",
          }}
        >
          {/* Network pattern overlay */}
          <svg
            className="w-full h-full opacity-30"
            viewBox="0 0 100 100"
            xmlns="http://www.w3.org/2000/svg"
          >
            <defs>
              <pattern
                id="grid"
                width="10"
                height="10"
                patternUnits="userSpaceOnUse"
              >
                <path
                  d="M 10 0 L 0 0 0 10"
                  fill="none"
                  stroke="#4F8FEA"
                  strokeWidth="0.2"
                />
              </pattern>
            </defs>
            <rect width="100" height="100" fill="url(#grid)" />

            {/* Random network lines and nodes */}
            {[...Array(15)].map((_, i) => (
              <line
                key={i}
                x1={Math.random() * 100}
                y1={Math.random() * 100}
                x2={Math.random() * 100}
                y2={Math.random() * 100}
                stroke="#4F8FEA"
                strokeWidth="0.2"
                opacity={Math.random() * 0.5 + 0.5}
              />
            ))}
            {[...Array(15)].map((_, i) => (
              <circle
                key={i + "node"}
                cx={Math.random() * 100}
                cy={Math.random() * 100}
                r={Math.random() * 1 + 0.5}
                fill="#4F8FEA"
                opacity={Math.random() * 0.5 + 0.5}
              />
            ))}
          </svg>
        </div>
      </div>

      {/* White side panel */}
      <div className="absolute left-0 top-0 bottom-0 bg-white w-1/4 z-10">
        <div className="pl-8 pt-16">
          <h1 className="text-5xl font-bold tracking-tight">CLOUD COST</h1>
          <h1 className="text-5xl font-bold tracking-tight mt-2">EFFICIENCY</h1>
          <h1 className="text-5xl font-bold tracking-tight mt-2">REPORT</h1>

          <h2 className="text-2xl font-semibold mt-8">
            {organizationName.toUpperCase()}
          </h2>

          <p className="text-lg mt-6">{reportDate}</p>

          <p className="text-sm text-gray-500 absolute bottom-8">
            Generated by MakeStuffGo
          </p>
        </div>
      </div>

      {/* Central visualization */}
      <div className="absolute left-1/4 right-0 top-0 bottom-0 flex items-center justify-center">
        <div className="w-1/2 h-1/2 relative">
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="w-64 h-64 rounded-full bg-blue-500 bg-opacity-10 flex items-center justify-center">
              <div className="w-48 h-48 rounded-full bg-blue-500 bg-opacity-20 flex items-center justify-center">
                <div className="w-32 h-32 rounded-full bg-blue-500 bg-opacity-30 flex items-center justify-center">
                  <div className="w-16 h-16 rounded-full bg-blue-500 bg-opacity-40"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Company logo */}
      <div className="absolute bottom-8 right-8 z-20">
        <h2 className="text-4xl font-bold text-white">MakeStuffGo</h2>
      </div>
    </div>
  )
}

export default MVPCoverPage
